title: Pratik Pranav
logo: /assets/profile.jpeg
google_analytics:
theme: jekyll-theme-minimal

twitter_username: PratikPranav11
github_username:  pratkpranav

url: "https://pratkpranav@github.io" 
email: pratkpranav@gmail.com
description: My Portfolio
