title: Pratik Pranav
logo: /assets/profile.jpeg
description: pratkpranav[at]gmail.com

url: "https://pratkpranav@github.io" 
email: pratkpranav@gmail.com


google_analytics:
theme: jekyll-theme-minimal
